services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: drawing-board-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_PATH=/data/drawing-board.db
      - SESSION_SECRET=your-secret-key-change-in-production
    volumes:
      - backend_data:/data
    networks:
      - drawing-board-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: drawing-board-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - drawing-board-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  backend_data:
    driver: local

networks:
  drawing-board-network:
    driver: bridge
